version: "3.6"
services:
  nginx:
    build: docker/nginx
    container_name: nginx_gmg
    ports:
      - "80:80"
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python

  python:
    build: docker/python
    container_name: python_gmg
    working_dir: /code
    restart: always
    volumes:
      - .:/code
    depends_on:
      - mysql

  mysql:
    build: docker/mysql
    container_name: mysql_gmg
    volumes:
        - ./docker/data/db:/var/lib/mysql
        - .:/code
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=asdgl
        - MYSQL_DATABASE=games
        - MYSQL_USER=game
        - MYSQL_PASSWORD=azerty
