version: "3.6"
services:
  nginx: # Name of the service. Used for communication between container, in fact in any configuration.
    build: Docker/nginx # let's override with our configuration in the docker file in this folder
    container_name: nginx_gmg
    ports:
      - "80:80"
    volumes:
      - ./Docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on: # Tells Docker that we need to wait and allow the given container to be accessible by the other one
      - python

  python:
      build: Docker/python
      container_name: python_gmg
      working_dir: /code
      volumes:
        - ./src:/code
      depends_on:
        - mysql

  mysql:
      image: mysql:latest
      container_name: mysql_gmg
      volumes:
          - ./docker/data/db:/var/lib/mysql
      command: "--default-authentication-plugin=mysql_native_password"
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=asdgl
          - MYSQL_DATABASE=adppc
          - MYSQL_USER=adppc
          - MYSQL_PASSWORD=azerty
