version: '2.1'
executors:
  python:
    docker:
      - image: python:latest
    working_directory: ~/repo

jobs:
  unittest:
    executor: python
    steps:
      - checkout
      - run:
          name: Run Unittest
          command: python3 -m unittest discover .

  linter:
    executor: python
    steps:
      - checkout  
      - run:
          name: Install pylint
          command: pip3 install pylint
      - run:
          name: Run pylint
          command: pip3 install --no-cache-dir  -r docker/python/requirements.txt && pylint --rcfile=standard.rc src/ ./app.py

workflows:
  version: '2.1'
  Code quality:
    jobs:
      - linter
      - unittest