version: '2.1'
executors:
  python:
    docker:
      - image: python:3.7
        name: python
        environment:
          DATABASE_URL: mysql://game:azerty@mysql:3306/games?serverVersion=5.7&charset=utf8
      - image: mysql:8
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
    working_directory: ~/repo
    resource_class: medium

commands:
  extra_checkout:
    description: Add extra packages and apps.
    steps:
      - checkout
      - run:
          name: "Install requirements for checkout"
          command: |
            apt update && apt install -y git openssh-client curl make nano libzip-dev
      - run:
          name: "Install required Python packages"
          command: |
            cd docker/python && pip3 install --no-cache-dir  -r requirements.txt && cd ../.. && gunicorn --workers=1 --bind=0.0.0.0:9000 app:app

jobs:
  unittest:
    executor: python
    steps:
      - checkout
      - run:
          name: Unit tests
          command: make test_command_sql && make test_command_python

  linter:
    executor: python
    steps:
      - checkout  
      - run:
          name: Install pylint
          command: pip3 install pylint
      - run:
          name: Run pylint
          command: pylint --rcfile=standard.rc src/ ./app.py

workflows:
  version: '2.1'
  Code quality:
    jobs:
      - linter
      - unittest