# Use the default image. Do not use like those guys who use a Linux distro then install nginx
FROM mysql:8

# Install nano because using vi is like using a donkey at the age of intergalactic travel
RUN apt-get update && apt-get -q -y install nano make
